apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: install-aimanager-on-existing-k8s
spec:
  params:
    - name: kubeConfigFile
      description: KubeConfig file name.
      type: string
      default: "kubeconfig"
    - name: aiopsVersion
      description: aiops version.
      type: string
      default: "v3.3"
    - name: aiopsNamespace
      description: aiops install namespace.
      type: string
      default: "cp4waiops"
    - name: clusterDomainName
      description: Cluster domain name.
      type: string
      default: ""
    - name: clusterPort
      description: Cluster port.
      type: string
      default: ""
    - name: zenEnabled
      description: Enable zen when install Bedrock.
      type: string
      default: "true"
  workspaces:
    - name: git-cred
    - name: kubeconfig
      optional: true
    - name: install-env
    - name: install-workspace
  tasks:

    - name: fetch-bedrock-install-script
      params:
        - name: url
          value: 'https://github.ibm.com/moyingbj/cs-dev-tools.git'
        - name: revision
          value: project-k
        - name: deleteExisting
          value: "true"
      taskRef:
        name: git-clone
      workspaces:
        - name: basic-auth
          workspace: git-cred
        - name: output
          workspace: install-workspace
          subPath: cs-dev-tools

    - name: install-bedrock
      runAfter:
        - fetch-bedrock-install-script
      params:
        - name: kubeConfigFile
          value: $(params.kubeConfigFile)
        - name: clusterDomainName
          value: $(params.clusterDomainName)
        - name: clusterPort
          value: $(params.clusterPort)
        - name: catsrcTag
          value: cd-20220406-1616
        - name: zenEnabled
          value: $(params.zenEnabled)
      taskRef:
        kind: Task
        name: cp-install-bedrock
      timeout: 100m
      workspaces:
        - name: install-env
          workspace: install-env
        - name: install-repo
          workspace: install-workspace
          subPath: cs-dev-tools
        - name: kubeconfig
          workspace: kubeconfig

    - name: fetch-aimanager-install-script
      runAfter:
        - install-bedrock
      params:
        - name: url
          value: 'https://github.ibm.com/gyliu/byoc.git'
        - name: revision
          value: main
        - name: deleteExisting
          value: "true"
      taskRef:
        name: git-clone
      workspaces:
        - name: basic-auth
          workspace: git-cred
        - name: output
          workspace: install-workspace
          subPath: byoc

    - name: install-aimanager
      runAfter:
        - fetch-aimanager-install-script
      params:
        - name: kubeConfigFile
          value: $(params.kubeConfigFile)
        - name: aiopsVersion
          value: $(params.aiopsVersion)
        - name: aiopsNamespace
          value: $(params.aiopsNamespace)
      taskRef:
        kind: Task
        name: cp-install-aimanager
      timeout: 120m
      workspaces:
        - name: install-env
          workspace: install-env
        - name: install-repo
          workspace: install-workspace
          subPath: byoc
        - name: kubeconfig
          workspace: kubeconfig
      