apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4waiops-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: argocd.allowLocalDeploy
        value: "false"
      - name: argocd.cluster
        value: kubernetes
      - name: cp4waiops.eventManager.enabled
        value: "false"
      - name: cp4waiops.version
        value: v3.4
      - name: rookceph.enabled
        value: "false"
      valueFiles:
      - values.yaml
      values: |-
        globalImagePullSecrets:
        - registry: REGISTRY
          username: USERNAME
          password: PASSWORD
        cp4waiops:
          repoURL: https://gitlab.HOSTNAME:9043/root/cp4waiops-gitops.git
          targetRevision: HEAD
        storageClass: STORAGECLASS
        storageClassLargeBlock: STORAGECLASSBLOCK
    path: config/all-in-one
    repoURL: https://gitlab.HOSTNAME:9043/root/cp4waiops-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
