apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: aiops-mirror-image
spec:
  workspaces:
    - name: install-env
  tasks:

    - name: aiops-mirror-image
      taskRef:
        kind: Task
        name: aiops-mirror-image
      timeout: 200m
      workspaces:
        - name: install-env
          workspace: install-env

    - name: install-applicationset
      runAfter:
        - aiops-mirror-image
      taskRef:
        kind: Task
        name: applicationset-install
      workspaces:
        - name: install-env
          workspace: install-env
