apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitops-install-online-task
spec:
  workspaces:
    - name: install-env
  tasks:

    - name: bootcluster-mirror-image
      taskRef:
        kind: Task
        name: bootcluster-mirror-image
      timeout: 200m
      workspaces:
        - name: install-env
          workspace: install-env

    - name: push-gitops-code-to-git
      runAfter:
        - bootcluster-mirror-image
      taskRef:
        kind: Task
        name: push-code-to-git
      workspaces:
        - name: install-env
          workspace: install-env
    
    - name: argocd-gitlab-connect
      runAfter:
        - push-gitops-code-to-git
      taskRef:
        kind: Task
        name: argocd-gitlab-connect
      workspaces:
        - name: install-env
          workspace: install-env
