apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitops-install-online-task
spec:
  workspaces:
    - name: install-env
    - name: install-workspace
  tasks:

    - name: bootcluster-mirror-image
      taskRef:
        kind: Task
        name: bootcluster-mirror-image
      timeout: 200m
      workspaces:
        - name: install-env
          workspace: install-env

    - name: aiops-mirror-image
      taskRef:
        kind: Task
        name: aiops-mirror-image
      timeout: 200m
      workspaces:
        - name: install-env
          workspace: install-env

    - name: fetch-cp4waiops-gitops-code
      params:
        - name: url
          value: 'https://github.com/IBM/cp4waiops-gitops.git'
        - name: revision
          value: main
        - name: deleteExisting
          value: "true"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: install-workspace
          subPath: cp4waiops-gitops

    - name: push-gitops-code-to-git
      runAfter:
        - fetch-cp4waiops-gitops-code
      taskRef:
        kind: Task
        name: push-code-to-git
      workspaces:
        - name: install-env
          workspace: install-env
        - name: install-repo
          workspace: install-workspace
          subPath: cp4waiops-gitops

    - name: install-applicationset
      runAfter:
        - push-gitops-code-to-git
      taskRef:
        kind: Task
        name: applicationset-install
      workspaces:
        - name: install-env
          workspace: install-env
