---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-pipeline
subjects:
  - kind: ServiceAccount
    name: tekton-pipeline
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
