actions:
  metadata:
    name: cp4waiopsGitopsSetup
    description: The actions to prepare for installing gitops for Watson AIOps in a restricted network
  actionDefs:
# Required action
    configureClusterAirgap:
      metadata:
        name: "configureClusterAirgap"
        description: "configures global pullsecret and imagesourcecontentpolicy"
        case.launcher.type: "script"
        case.cli.alias: "configure-cluster-airgap"
      roles:
      - clusterAdmin
      requires:
        and:
        - "/case/prereqs/k8sDistros/kubernetes"
        - "/case/prereqs/k8sDistros/openshift"
      k8sPermissions:
        rules: []
# Required action
    configureCredsAirgap:
      metadata:
        name: "configureCredsAirgap"
        description: "configures login credentails for an image registry"
        case.launcher.type: "script"
        case.cli.alias: "configure-creds-airgap"
      roles:
      - clusterAdmin
      k8sPermissions:
        rules: []
# Required action
    mirrorImages:
      metadata:
        name: "mirrorImages"
        description: "Mirrors the images to a local registry using oc"
        case.launcher.type: "script"
        case.cli.alias: "mirror-images"
      roles:
      - clusterAdmin
      requires:
        and:
          - "/case/prereqs/client/oc"
          - "/case/prereqs/client/skopeo"
      k8sPermissions:
        rules: []
# init local docker registry
    initRegistry:
      metadata:
        name: "initRegistry"
        description: "Initialize a local docker registry"
        case.launcher.type: "script"
        case.cli.alias: "init-registry"
      roles:
      - clusterAdmin
      requires:
        and:
          - "/case/prereqs/client/openssl"
          - "/case/prereqs/client/htpasswd"
      k8sPermissions:
        rules: []
# start local docker registry
    startRegistry:
      metadata:
        name: "startRegistry"
        description: "Start a local docker registry container"
        case.launcher.type: "script"
        case.cli.alias: "start-registry"
      roles:
      - clusterAdmin
      requires:
        or:
          - "/case/prereqs/client/podman"
          - "/case/prereqs/client/docker"
      k8sPermissions:
        rules: []
# stop local docker registry
    stopRegistry:
      metadata:
        name: "stopRegistry"
        description: "Start a local docker registry container"
        case.launcher.type: "script"
        case.cli.alias: "stop-registry"
      roles:
      - clusterAdmin
      requires:
        or:
          - "/case/prereqs/client/podman"
          - "/case/prereqs/client/docker"
      k8sPermissions:
        rules: []        
# Required action - OLM enabled
    installGitops:
      metadata:
        name: "installGitops"
        description: "Installs Gitops"
        case.launcher.type: "script"
        case.cli.alias: "install-gitops"
      roles:
        - clusterAdmin
      requires:
        and:
          - "/case/prereqs/k8sDistros/kubernetes"
          - "/case/prereqs/k8sDistros/openshift"
      k8sPermissions:
        rules: []
