resources:
  resourceDefs:
    cases:
    - case: ibm-watson-ai-manager
      version: '>= 1.4.0 < 1.4.1'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-watson-aiops-ui-operator-case
      version: '>= 1.3.1 < 1.3.2'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-management-kong
      version: '>= 3.4.0 < 3.4.1'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-asm-operator-case
      version: '>= 2.7.0 < 2.7.1'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-secure-tunnel
      version: '>= 3.4.0 < 3.4.1'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-postgreservice
      version: '>= 1.2.0 < 1.2.1'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-aiops-ir-core-operator
      version: '>= 2.1.0 < 2.1.1'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-aiops-lifecycle
      version: '>= 2.1.0 < 2.1.1'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-aiops-analytics
      version: '>= 2.1.0 < 2.1.1'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-aiopsedge-bundle
      version: '>= 1.2.0 < 1.2.1'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-cp-common-services
      version: '>= 1.11.1 < 2.0.0'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-cp-automation-foundation
      version: '>= 1.3.4 < 2.0.0'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-couchdb
      version: '>= 1.0.13 < 1.0.14'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-cloud-databases-redis
      version: '>= 1.4.5 < 1.4.6'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    - case: ibm-cloud-native-postgresql
      version: '>= 4.0.8 < 4.0.9'
      mediaType: application/vnd.case.core.v1
      repositoryURLs:
      - https://raw.githubusercontent.com/IBM/cloud-pak/master/repo/case
    files:
    - mediaType: application/vnd.case.resource.script.bash.v1
      ref: airgap.sh
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: catalog_source.yaml
    - mediaType: application/vnd.case.resource.script.bash.v1
      ref: launch-impl.sh
    - mediaType: application/vnd.case.resource.script.bash.v1+launcher
      ref: launch.sh
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: subscription.yaml
    - ref: gitops/application.yaml
      mediaType: application/vnd.case.resource.k8s.v1+yaml
    - ref: gitops/install.sh
      mediaType: application/vnd.case.resource.script.bash.v1
    - ref: gitops/config.sh
      mediaType: application/vnd.case.resource.script.bash.v1
    - ref: gitops/load-image.sh
      mediaType: application/vnd.case.resource.script.bash.v1
    - ref: gitops/launch-registry.sh
      mediaType: application/vnd.case.resource.script.bash.v1
    containerImages:
    - image: cpopen/ibm-aiops-orchestrator-bundle
      digest: sha256:a34cf98ddb2ea747d9bb0e3baf0b5c0b87ae93841a9eb6be98ed73f67fe1c8e7
      tag: v3.4.0-20220617.1434-a34cf98dd
      mediaType: application/vnd.docker.distribution.manifest.v2
      platform:
        architecture: amd64
        os: linux
      registries:
      - host: icr.io
      metadata:
        operators_operatorframework_io:
          bundle:
            mediaType: registry+v1
            cpcicd_ibm_com:
              targetCatalogs:
                catalogRefs:
                - ibm-public: {}
    - image: cpopen/ibm-cp-waiops-case-bundle-catalog
      digest: sha256:c724f40aecab317f3b624090f4de5dcbf201ab2aaf226513de5f049901d30189
      tag: v3.4.0-20220617.1434-c724f40ae
      mediaType: application/vnd.docker.distribution.manifest.list.v2
      registries:
      - host: icr.io
      metadata:
        operators_operatorframework_io:
          catalog:
            mediaType: registry+v1
      manifests:
      - digest: sha256:6c10e87e44fdc9d1af04dd950a74474fba4671e659522f7acee12f867bde4e97
        mediaType: application/vnd.docker.distribution.manifest.v2
        tag: v3.4.0-20220617.1434-c724f40ae-linux.amd64
        platform:
          architecture: amd64
          os: linux
    - image: cpopen/ibm-aiops-orchestrator
      digest: sha256:b2d8e0138b711a5497898d945815ab3c0d59038b519fbfcd153bd9f832ff97ae
      tag: v3.4.0-20220617.1434-b2d8e0138
      mediaType: application/vnd.docker.distribution.manifest.list.v2
      metadata:
        name: ibm_aiops_orchestrator
        displayName: cpopen/ibm-aiops-orchestrator
      registries:
      - host: icr.io
      manifests:
      - digest: sha256:bb7d8cfbbd099b1e32315c7c9ae68dc8423d6bfdfa46c5678e49141d8d5d0ca9
        mediaType: application/vnd.docker.distribution.manifest.v2
        tag: v3.4.0-20220617.1434-b2d8e0138-linux.amd64
        platform:
          architecture: amd64
          os: linux
