###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2019. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: operator-shared-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "ecm-openshift-nfs"
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 20.0.1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
