---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mirror-image
spec:
  description: >-
    Task to Mirror Image.
  params:
    - name: registry
      description: local registry name.
      type: string
  steps:
    - name: mirror-image
      image: alpine
      env:
      - name: REGISTRY
        value: "$(params.registry)"
      script: |
        #!/usr/bin/env sh
        set -eu

        oc ibm-pak generate mirror-manifests ibm-cp-waiops dormer1.fyre.ibm.com:5003
        oc image mirror -f ~/.ibm-pak/data/mirror/ibm-cp-waiops/1.3.0/images-mapping.txt --filter-by-os=.* --insecure --skip-multiple-scopes --max-per-registry=1
