{{- if .Values.internalbuild }}
apiVersion: batch/v1
kind: Job
metadata:
  name: gobal-image-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  namespace: {{.Values.spec.aiManager.namespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          command:
            - /bin/sh
            - -c
            - |
              set -eo pipefail
              set -x

              ARTIFACTORY_EMAIL={{.Values.ARTIFACTORY_EMAIL}}
              ARTIFACTORY_KEY={{.Values.ARTIFACTORY_KEY}}
              DOCKER_USER={{.Values.DOCKER_USER}}
              DOCKER_KEY={{.Values.DOCKER_KEY}}
              CP_STG_USER={{.Values.CP_STG_USER}}
              CP_PROD_USER={{.Values.CP_PROD_USER}}
              CP_PROD_KEY={{.Values.CP_PROD_KEY}}
              CP_STG_KEY={{.Values.CP_STG_KEY}}

              if [[ "$ARTIFACTORY_EMAIL" == "" || "$ARTIFACTORY_KEY" == "" || "$CP_PROD_KEY" == "" || "$CP_STG_KEY" == "" ]]; then
                  echo "Need image pull secret for internal build: ARTIFACTORY_EMAIL,ARTIFACTORY_KEY,CP_PROD_KEY,CP_STG_KEY"
                  exit 1
              fi

              ARTIFACTORY_AUTH="$ARTIFACTORY_EMAIL:$ARTIFACTORY_KEY"
              DOCKER_AUTH="$DOCKER_USER:$DOCKER_KEY"
              CP_STG_USER="${CP_STG_USER:=iamapikey}"
              CP_PROD_USER="${CP_PROD_USER:=iamapikey}"
              CP_PROD_AUTH="$CP_PROD_USER:$CP_PROD_KEY"
              CP_STG_AUTH="$CP_STG_USER:$CP_STG_KEY"

              # Extract the existing pull secret from cluster
              rm -rf ${HOME}/.dockerconfigjson
              oc extract secret/pull-secret -n openshift-config --to ${HOME} --confirm
              if [[ $? -ne 0 ]]; then
                  logger "[ERROR] Failed to extract existing pull-secret!"
                  return 1
              fi

              # Patch .dockerconfigjson with user values
              oc registry login --registry hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com \
              --auth-basic=$ARTIFACTORY_AUTH \
              --to=${HOME}/.dockerconfigjson

              oc registry login --registry hyc-cloud-private-daily-docker-local.artifactory.swg-devops.com \
              --auth-basic=$ARTIFACTORY_AUTH \
              --to=${HOME}/.dockerconfigjson

              oc registry login --registry hyc-hdm-devops-team-docker-local.artifactory.swg-devops.com \
              --auth-basic=$ARTIFACTORY_AUTH \
              --to=${HOME}/.dockerconfigjson

              oc registry login --registry docker.io \
              --auth-basic=$DOCKER_AUTH \
              --to=${HOME}/.dockerconfigjson

              oc registry login --registry cp.icr.io \
              --auth-basic=$CP_PROD_AUTH \
              --to=${HOME}/.dockerconfigjson

              oc registry login --registry cp.stg.icr.io \
              --auth-basic=$CP_STG_AUTH \
              --to=${HOME}/.dockerconfigjson

              # Apply the new secret
              oc set data secret/pull-secret --from-file .dockerconfigjson=${HOME}/.dockerconfigjson -n openshift-config

              wait_time=40
              # master nodes
              sleep $wait_time
              num_masters=$(oc get machineconfigpools master --no-headers -o custom-columns=":status.machineCount")
              num_masters_ready=$(oc get machineconfigpools master --no-headers -o custom-columns=":status.readyMachineCount")
              # worker nodes
              num_workers=$(oc get machineconfigpools worker --no-headers -o custom-columns=":status.machineCount")
              num_workers_ready=$(oc get machineconfigpools worker --no-headers -o custom-columns=":status.readyMachineCount")
              attempt=1
              if [ $num_masters_ready -lt $num_masters ]; then
                while [[ $num_masters_ready -lt $num_masters ]] && [[ $attempt -le $attempts ]]
                do
                  echo "Not all master nodes updated"
                  echo "$num_masters_ready/$num_masters master nodes currently ready - $attempt/$attempts"
                  ((attempt=$attempt+1))
                  sleep $wait_time
                  num_masters_ready=$(oc get machineconfigpools master --no-headers -o custom-columns=":status.readyMachineCount")
                done
              else
                echo "All master nodes updated"
              fi
              attempt=1
              if [ $num_workers_ready -lt $num_workers ]; then
                while [[ $num_workers_ready -lt $num_workers ]] && [[ $attempt -le $attempts ]]
                do
                  echo "Not all worker nodes updated"
                  echo "$num_workers_ready/$num_workers worker nodes currently ready - $attempt/$attempts"
                  ((attempt=$attempt+1))
                  sleep $wait_time
                  num_workers_ready=$(oc get machineconfigpools worker --no-headers -o custom-columns=":status.readyMachineCount")
                done
              else
                echo "All worker nodes updated"
              fi

      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin-ai
  backoffLimit: 1
{{- end }}