{{- if .Values.cp4waiops.eventManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventmanager-app
metadata:
  name: eventmanagerapp
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  destination:
    namespace: '{{ .Values.cp4waiops.eventManager.namespace }}'
    server: '{{ `{{server}}` }}'
  project: default
  source:
    path: config/3.3/eventManager
    repoURL: https://github.com/liyanwei93/cp4waiops-gitops
    targetRevision: release-3.3
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: spec.dockerUsername
          value: '{{ .Values.cp4waiops.dockerUsername }}'
        - name: spec.dockerPassword
          value: '{{ .Values.cp4waiops.dockerPassword }}'
        - name: spec.imageCatalog
          value: '{{ .Values.cp4waiops.imageCatalog }}'
        - name: spec.storageClass
          value: '{{ .Values.cp4waiops.storageClass }}'
        - name: spec.storageClassLargeBlock
          value: '{{ .Values.cp4waiops.storageClassLargeBlock }}'
        - name: spec.eventManager.version
          value: '{{ .Values.cp4waiops.eventManager.version }}'
        - name: spec.eventManager.clusterDomain
          value: '{{ .Values.cp4waiops.eventManager.clusterDomain }}'
        - name: spec.eventManager.channel
          value: '{{ .Values.cp4waiops.eventManager.channel }}'
        - name: spec.eventManager.deploymentType
          value: '{{ .Values.cp4waiops.eventManager.deploymentType }}'
        - name: spec.eventManager.namespace
          value: '{{ .Values.cp4waiops.eventManager.namespace }}'              
  ignoreDifferences:
    - group: noi.ibm.com/v1beta1
      jsonPointers:
        - /spec
      kind: NOI
    - group: v1
      jsonPointers:
        - /imagePullSecrets
      kind: ServiceAccount
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
